services:

  postgres:

    image: postgres:17.6
    container_name: investments-db
    environment:
      POSTGRES_DB: investments
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"

    networks:
      - backend

  pgadmin:

    image: dpage/pgadmin4:9.8.0
    ports:
      - "8123:80"
      - "8443:443"

    environment:
      - PGADMIN_DEFAULT_EMAIL=web@ufop.edu.br
      - PGADMIN_DEFAULT_PASSWORD=123456

    networks:
      - backend

networks:
  frontend:
  backend: